// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    String baseURL = "http://localhost/prog8170a04/getQuote.html";

    [Test]
    public void quote001_InputValidDataAge15Exp3Acc0_OutputErrorInvalidAge()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "15";
        String experience = "3";
        String accidentsNo = "0";

        String quoteValue = "Please enter a value greater than or equal to 16.";
        String errorType = "Age";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);

    }//End of Test1
    [Test]
    public void quote002_InputValidDataAge25Exp0Acc1_OutputQuote6000()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "25";
        String experience = "0";
        String accidentsNo = "1";

        String quoteValue = "$6000";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);

    }//End of Test2
    [Test]
    public void quote003_InputValidDataAge25Exp1Acc1_OutputQuote4500()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "25";
        String experience = "1";
        String accidentsNo = "1";

        String quoteValue = "$4500";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);

    }//End of Test3
    [Test]
    public void quote004_InputValidDataAge25Exp3Acc0_OutputQuote4500()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "25";
        String experience = "3";
        String accidentsNo = "0";

        String quoteValue = "$4500";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);


    }//End of Test4
    [Test]
    public void quote005_InputValidDataAge30Exp2Acc1_OutputQuote3285()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "30";
        String experience = "2";
        String accidentsNo = "1";

        String quoteValue = "$3285";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test5
    [Test]
    public void quote006_InputValidDataAge27Exp10Acc1_OutputQuote3000()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "27";
        String experience = "10";
        String accidentsNo = "1";

        String quoteValue = "$3000";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test6

    [Test]
    public void quote007_InputValidDataAge27Exp10Acc1_OutputQuote3000()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "30";
        String experience = "10";
        String accidentsNo = "1";

        String quoteValue = "$2190";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test7

    [Test]
    public void quote008_InputValidDataAge35Exp10Acc4_OutputHighAccidents()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "35";
        String experience = "10";
        String accidentsNo = "4";

        String quoteValue = "No Insurance for you!!  Too many accidents - go take a course!";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test8

    [Test]
    public void quote009_InputValidDataAge25Exp3Acc2_OutputQuote4500()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "25";
        String experience = "3";
        String accidentsNo = "2";

        String quoteValue = "$4500";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test9

    [Test]
    public void quote010_InputValidDataPhNo1231231234Age27Exp3Acc0_OutputErrorPhoneNumberFormat()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "1231231234";
        String email = "asad@test.com";

        String age = "27";
        String experience = "3";
        String accidentsNo = "0";

        String quoteValue = "Phone Number must follow the patterns 111-111-1111 or (111)111-1111";
        String errorType = "PhoneFormat";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test10

    [Test]
    public void quote011_InputValidDataEmailasadAge28Exp3Acc0_OutputErrorEmailFormat()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad";

        String age = "28";
        String experience = "3";
        String accidentsNo = "0";

        String quoteValue = "Must be a valid email address";
        String errorType = "Email";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test11

    [Test]
    public void quote012_InputValidDataPostalN3LY31Age35Exp17Acc0_OutputErrorPostalCodeFormat()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "35";
        String experience = "17";
        String accidentsNo = "0";

        String quoteValue = "Postal Code must follow the pattern A1A 1A1";
        String errorType = "PostalCode";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test12

    [Test]
    public void quote013_InputValidDataAgeEmptyExp5Acc0_OutputErrorAgeMandatory()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "";
        String experience = "5";
        String accidentsNo = "0";

        String quoteValue = "Age (>=16) is required";
        String errorType = "Age";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test13

    [Test]
    public void quote014_InputValidDataAge37Exp8AccEmpty_OutputErrorAccNoMandatory()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "37";
        String experience = "8";
        String accidentsNo = "";

        String quoteValue = "Number of accidents is required";
        String errorType = "AccidentsNoEmpty";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test14

    [Test]
    public void quote015_InputValidDataAge45ExpEmptyAcc0_OutputErrorExpMandatory()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "45";
        String experience = "";
        String accidentsNo = "0";

        String quoteValue = "Years of experience is required";
        String errorType = "ExperienceEmpty";

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test15

    [Test]
    public void quote016_InputValidDataAge16Exp3Acc0_OutputInvalidAgeExpCombination()
    {
        String firstName = "Asad";
        String lastName = "Ashraf";
        String address = "Conestoga";
        String city = "Waterloo";
        String postalCode = "N3Y 3Y3";
        String phone = "123-123-1234";
        String email = "asad@test.com";

        String age = "16";
        String experience = "3";
        String accidentsNo = "0";

        String quoteValue = "No Insurance for you!! Driver Age / Experience Not Correct";
        String errorType = null;

        sampleTest(firstName, lastName, address, city, postalCode, phone, email, age, experience, accidentsNo, quoteValue, errorType);
    }//End of Test16



    public void sampleTest(String firstName, String lastName, String address, String city, String postalCode, String phone, String email, String age, String exp, String accNo, String quoteValue, String errorType)
    {
        // Arrange
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(1423, 693);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys(firstName);
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys(lastName);
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys(address);
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys(city);
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys(postalCode);
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys(phone);
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys(email);
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys(age);
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys(exp);
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys(accNo);
        driver.FindElement(By.CssSelector("body")).Click();

        // Act
        driver.FindElement(By.Id("btnSubmit")).Click();

        // Assert
        String value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
        String text = null;
        if (value.Length  > 0)
        {
            Assert.That(value, Is.EqualTo(quoteValue));
        } else
        {
            if(errorType == "PhoneFormat")
            {
                text = driver.FindElement(By.Id("phone-error")).Text;
            }
            if (errorType == "Age")
            {
                text = driver.FindElement(By.Id("age-error")).Text;
            }
            if (errorType == "Email")
            {
                text = driver.FindElement(By.Id("email-error")).Text;
            }
            if (errorType == "PostalCode")
            {
                text = driver.FindElement(By.Id("postalCode-error")).Text;
            }
            if (errorType == "AccidentsNoEmpty")
            {
                text = driver.FindElement(By.Id("accidents-error")).Text;
            }
            if (errorType == "ExperienceEmpty")
            {
                text = driver.FindElement(By.Id("experience-error")).Text;
            }

            Assert.That(text, Is.EqualTo(quoteValue));
        }
    }//End of SampleTest
}// End of Class 1

